exclude: "docs|node_modules|migrations|.git|.tox"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: requirements-txt-fixer
  - repo: local
    hooks:
      - id: format
        name: format
        entry: bash scripts/format.sh
        pass_filenames: false
        language: system
      - id: lint
        name: lint
        entry: bash scripts/lint.sh
        pass_filenames: false
        language: system
      - id: test
        name: test
        entry: bash scripts/test.sh
        pass_filenames: false
        language: system
      - id: test_cov
        name: test_cov
        entry: bash scripts/test_cov.sh
        pass_filenames: false
        language: system
      - id: create_coverage_badge
        name: create_coverage_badge
        entry: bash scripts/create_coverage_badge.sh
        pass_filenames: false
        language: system
