version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    restart: always
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - .:/app:z
    env_file:
      - .env
