apiVersion: v1
kind: Service
metadata:
  name: dns-api-svc
spec:
  selector:
    app: dns-api
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-api
  labels:
    app: dns-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-api
  template:
    metadata:
      labels:
        app: dns-api
    spec:
      containers:
        - name: dns-api
          image: dnau/dns-info-researcher:1.0.0
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
