name: Tests

on: [pull_request]

env:
  TITLE: Random
  APP_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.9.7
      - name: Install dependencies
        run: |
          pip install -r requirements/local.txt
      - name: lint
        run: |
          chmod +x "${GITHUB_WORKSPACE}/scripts/lint.sh"
          "${GITHUB_WORKSPACE}/scripts/lint.sh"
      - name: test
        run: |
          chmod +x "${GITHUB_WORKSPACE}/scripts/test.sh"
          "${GITHUB_WORKSPACE}/scripts/test.sh"
      - name: test_cov
        run: |
          chmod +x "${GITHUB_WORKSPACE}/scripts/test_cov.sh"
          "${GITHUB_WORKSPACE}/scripts/test_cov.sh"
