name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements/local.txt
      - name: mypy
        run: |
          mypy .
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.15.3
      - name: pytest
        run: |
          pytest .
